# docker-compose.yml
version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: InclusiveInsights
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage volume
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
